name: AzenethShapes
favicon: null
layout_spectrum: 0.5770152523182333
typography_spectrum: 0.5938142451923341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5717076088767499
  lightness: 0.9332953030243516
  saturation: 0.3502776378300041
  rhythmicContrast: 0.543787992792204
purpose: []
