name: AzenethShapes
favicon: null
layout_spectrum: 0
typography_spectrum: 0.68964
title: Surfboards designed by Joseph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 0.9332953030243516
  saturation: 0
  rhythmicContrast: 0.543787992792204
purpose: []
